// code-graph · lib/signals.mjs — señales por archivo leídas del código: generado, reflexión/dinámico, recursión.
// Puro (sin DOM): recibe el texto y el IR del adaptador.

const GEN_NAME = [/\.(?:g|generated|designer)\.(?:cs|ts|js|dart|vb)$/i, /\.pb\.(?:go|cc|h)$/, /_pb2(?:_grpc)?\.pyi?$/, /\.min\.(?:js|css)$/, /\.pb\.(?:js|ts)$/, /(?:^|\/)(?:generated|__generated__|gen)\//i, /\.generated\./i, /Grpc\.java$/];
const GEN_MARK = /@generated|DO NOT EDIT|<auto-generated|auto-?generated|code generated by|generated by (?:the )?\w+|this file (?:is|was) (?:auto)?-?generated|archivo generado/i;

/** ¿Es código generado? Devuelve el motivo o null. */
export function generatedReason(id, raw) {
  for (const rx of GEN_NAME) if (rx.test(id)) return 'por el nombre del archivo';
  const head = raw.split('\n', 25).join('\n');
  const m = head.match(GEN_MARK); if (m) return `marca «${m[0].slice(0, 40)}» en la cabecera`;
  const lines = raw.split('\n');
  if (lines.length <= 3 && raw.length > 3000) return 'minificado (pocas líneas, muy largo)';
  return null;
}

// reflexión / ejecución dinámica por lenguaje: lo que el grafo estático NO puede seguir
const DYN = {
  javascript: [[/\brequire\(\s*(?!['"`])[^)]/, 'require(variable)'], [/\bimport\(\s*(?!['"`])[^)]/, 'import(variable)'], [/\beval\(/, 'eval'], [/\bnew\s+Function\(/, 'new Function'], [/\bReflect\.(?:get|apply|construct)\(/, 'Reflect']],
  csharp: [[/\bActivator\.CreateInstance\(/, 'Activator.CreateInstance'], [/\bType\.GetType\(/, 'Type.GetType'], [/\bAssembly\.(?:Load|LoadFrom|GetTypes)\(/, 'Assembly.Load'], [/\.GetMethod\(|\.GetProperty\(|\.Invoke\(/, 'reflexión (GetMethod/Invoke)']],
  java: [[/\bClass\.forName\(/, 'Class.forName'], [/\.getMethod\(|\.getDeclaredMethod\(|\.newInstance\(/, 'reflexión (getMethod/newInstance)'], [/\bServiceLoader\.load\(/, 'ServiceLoader']],
  kotlin: [[/\bClass\.forName\(|::class\.java\.get|\.newInstance\(/, 'reflexión']],
  python: [[/\bgetattr\(/, 'getattr'], [/\bimportlib\.import_module\(|\b__import__\(/, 'import dinámico'], [/\beval\(|\bexec\(/, 'eval/exec']],
  php: [[/\bnew\s+\$\w+|\$\w+::\w+\(|call_user_func/, 'clase/función dinámica'], [/\beval\(/, 'eval']],
  go: [[/\breflect\.\w+/, 'reflect'], [/\bplugin\.Open\(/, 'plugin.Open']],
  rust: [[/\blibloading\b|\bdlopen\b/, 'carga dinámica']],
  ruby: [[/\bsend\(|\bconstantize\b|\binstance_eval\b|\bconst_get\b/, 'metaprogramación']],
};
DYN.typescript = DYN.javascript;

/** usos dinámicos [{line, what}] (sobre el código ya sin comentarios) */
export function dynamicUses(code, lang) {
  const pats = DYN[lang]; if (!pats) return [];
  const out = [], lines = code.split('\n');
  for (let i = 0; i < lines.length && out.length < 12; i++) for (const [rx, what] of pats) if (rx.test(lines[i])) { out.push({ line: i + 1, what }); break; }
  return out;
}

/** cuerpo [inicio,fin) en líneas (0-based) de cada definición de función */
function bodies(lines, defs, lang) {
  const out = [];
  const py = lang === 'python';
  for (const d of defs) {
    if (!['function', 'method', 'const'].includes(d.kind)) continue;
    const s = d.line - 1; let e = s + 1;
    if (py) { const ind = lines[s].match(/^\s*/)[0].length; while (e < lines.length && (!lines[e].trim() || lines[e].match(/^\s*/)[0].length > ind)) e++; }
    else {
      let depth = 0, started = false, i = s;
      for (; i < Math.min(lines.length, s + 400); i++) {
        for (const ch of lines[i]) { if (ch === '{') { depth++; started = true; } else if (ch === '}') depth--; }
        if (started && depth <= 0) break;
        if (!started && i >= s + 2) break;
      }
      e = started ? i + 1 : s + 1;
    }
    out.push({ name: d.name, s, e });
  }
  return out;
}

/** recursión directa y mutua dentro de un archivo (grafo de llamadas por nombre) */
export function recursion(code, defs, lang) {
  if (!defs?.length) return [];
  const lines = code.split('\n'), fns = bodies(lines, defs, lang);
  if (!fns.length) return [];
  const names = new Set(fns.map((f) => f.name)), adj = new Map();
  for (const f of fns) {
    const called = new Set();
    for (let i = f.s; i < f.e && i < lines.length; i++) {
      let ln = lines[i]; if (i === f.s) ln = ln.replace(new RegExp(`\\b${f.name}\\b`), ' ');
      for (const m of ln.matchAll(/\b([A-Za-z_]\w*)\s*\(/g)) if (names.has(m[1])) called.add(m[1]);
    }
    adj.set(f.name, [...(adj.get(f.name) || []), ...called]);
  }
  const out = [];
  for (const [a, cs] of adj) if (cs.includes(a)) out.push({ kind: 'directa', names: [a], line: fns.find((f) => f.name === a).s + 1 });
  // Tarjan sobre funciones
  let idx = 0; const st = [], on = new Set(), ix = new Map(), lo = new Map();
  const go = (v) => {
    ix.set(v, idx); lo.set(v, idx); idx++; st.push(v); on.add(v);
    for (const w of adj.get(v) || []) { if (!ix.has(w)) { go(w); lo.set(v, Math.min(lo.get(v), lo.get(w))); } else if (on.has(w)) lo.set(v, Math.min(lo.get(v), ix.get(w))); }
    if (lo.get(v) === ix.get(v)) { const c = []; let w; do { w = st.pop(); on.delete(w); c.push(w); } while (w !== v); if (c.length > 1) out.push({ kind: 'mutua', names: c.sort(), line: Math.min(...c.map((n) => fns.find((f) => f.name === n).s + 1)) }); }
  };
  for (const v of adj.keys()) if (!ix.has(v)) go(v);
  return out.slice(0, 8);
}

/** carpetas que no son el producto (ejemplos, demos, datos de prueba, benchmarks, documentación, vendor) */
const AUX_DIR = /(?:^|\/)(?:examples?|samples?|demos?|fixtures?|playground|bench(?:marks?)?|docs?|vendor|third_party)(?:\/|$)/i;
/** marca `aux` en los archivos que viven en esas carpetas, salvo que sean la mayor parte del proyecto */
export function markAux(nodes, extra = [], off = false) {
  if (off) return 0;
  const files = nodes.filter((n) => n.kind === 'file' && !n.isTest), rx = extra.map((r) => new RegExp(r));
  const aux = files.filter((n) => AUX_DIR.test(n.id) || rx.some((r) => r.test(n.id)));
  if (!aux.length || files.length - aux.length < 3) return 0; // si casi todo vive ahí, es el proyecto mismo
  for (const n of aux) n.aux = AUX_DIR.exec(n.id)?.[0].replace(/\//g, '') || 'configurado';
  return aux.length;
}
